Directory/src/com/flowers/portal/vo/Order.java
package com.flowers.portal.vo;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import com.flowers.portal.util.Money;
import com.flowers.server.entity.Shop;


public class Order implements Serializable{
	private static final long serialVersionUID = 931996160281452222L;
	public static final String MESSAGE_TYPE = "0";
	public static final String SYSTEM_TYPE = "GENERAL";
	public static final String WIRE_SERVICE_CODE = "BMT";
	
	private Shop sendingShop;
	private Shop receivingShop;
	private Shop fulfillingShop;
	
	private String cardMessage;
	private Date captureDate;
	
	private String deliveryDate;
	private String specialInstruction;
	
	private Long ocasionId;
	private String facilityId;
	
	private Recipient recipient;
	
	private String trackingNumber;
	private String shipperCode;
	private String shippingMethod;
	private Date shippingDate;
	private String containsPerishables;
	
	private String productId;
	
	private List<DescribedProduct> describedProducts = new ArrayList<DescribedProduct>();
		
	//private long userId; 
	
//	private String cardMessage;
//	private String specialInstructions;
//	private Date deliveryDate;
	//private long myRatingId;
	//private String myComments;
	//private List<ProductCodification> products = new ArrayList<ProductCodification>();
	private String facility;
	
	private Money deliveryCharge;
	private Money subTotal;
	private Money grandTotal;
	private int quantity;
	
	
	public void setSendingShop(Shop sendingShop) {
		this.sendingShop = sendingShop;
	}
	
	public Shop getSendingShop() {
		return sendingShop;
	}
	
	public void setReceivingShop(Shop receivingShop) {
		this.receivingShop = receivingShop;
	}
	
	public Shop getReceivingShop() {
		return receivingShop;
	}
	
	public void setFulfillingShop(Shop fulfillingShop) {
		this.fulfillingShop = fulfillingShop;
	}
	
	public Shop getFulfillingShop() {
		return fulfillingShop;
	}
	
	public void setRecipient(Recipient recipient) {
		this.recipient = recipient;
	}
	
	public Recipient getRecipient() {
		return recipient;
	}

	public void setTrackingNumber(String trackingNumber) {
		this.trackingNumber = trackingNumber;
	}

	public String getTrackingNumber() {
		return trackingNumber;
	}

	public void setShipperCode(String shipperCode) {
		this.shipperCode = shipperCode;
	}

	public String getShipperCode() {
		return shipperCode;
	}

	public void setShippingMethod(String shippingMethod) {
		this.shippingMethod = shippingMethod;
	}

	public String getShippingMethod() {
		return shippingMethod;
	}

	public void setShippingDate(Date shippingDate) {
		this.shippingDate = shippingDate;
	}

	public Date getShippingDate() {
		return shippingDate;
	}

	public void setDeliveryDate(String deliveryDate) {
		this.deliveryDate = deliveryDate;
	}

	public String getDeliveryDate() {
		return deliveryDate;
	}

	public void setSpecialInstruction(String specialInstruction) {
		this.specialInstruction = specialInstruction;
	}

	public String getSpecialInstruction() {
		return specialInstruction;
	}

	public void setCaptureDate(Date captureDate) {
		this.captureDate = captureDate;
	}

	public Date getCaptureDate() {
		return captureDate;
	}

	public void setCardMessage(String cardMessage) {
		this.cardMessage = cardMessage;
	}

	public String getCardMessage() {
		return cardMessage;
	}

	public void setOcasionId(Long ocasionId) {
		this.ocasionId = ocasionId;
	}

	public Long getOcasionId() {
		return ocasionId;
	}
	
	public String getFacilityId() {
		return facilityId;
	}

	public void setFacilityId(String facilityId) {
		this.facilityId = facilityId;
	}

	public void setDescribedProducts(List<DescribedProduct> describedProducts) {
		this.describedProducts = describedProducts;
	}

	public List<DescribedProduct> getDescribedProducts() {
		return describedProducts;
	}

	public String getFacilityName() {
		return facility;
	}

	public void setFacilityName(String facility) {
		this.facility = facility;
	}

	public Money getDeliveryCharge() {
		return deliveryCharge;
	}

	public void setDeliveryCharge(Money deliveryCharge) {
		this.deliveryCharge = deliveryCharge;
	}

	public Money getSubTotal() {
		return subTotal;
	}

	public void setSubTotal(Money subTotal) {
		this.subTotal = subTotal;
	}

	public Money getGrandTotal() {
		return grandTotal;
	}

	public void setGrandTotal(Money grandTotal) {
		this.grandTotal = grandTotal;
	}

	public int getQuantity() {
		return quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	public String getProductId() {
		return productId;
	}

	public void setProductId(String productId) {
		this.productId = productId;
	}

	public String getContainsPerishables() {
		return containsPerishables;
	}

	public void setContainsPerishables(String containsPerishables) {
		this.containsPerishables = containsPerishables;
	}
	
}

Directory/src/com/flowers/portal/controller/BMSSearchController.java
package com.flowers.portal.controller;

import java.util.Properties;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.log4j.Logger;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.orm.hibernate5.HibernateTemplate;
import org.springframework.stereotype.Controller;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import com.flowers.portal.service.ControllerService;
import com.flowers.portal.service.PortalService;
import com.flowers.portal.service.SessionManager;
import com.flowers.portal.util.DateUtil;
import com.flowers.server.entity.LoginLog;
import com.flowers.server.entity.User;
import com.liferay.portal.kernel.util.Validator;
import com.liferay.portal.security.auth.AutoLoginException;

@Controller
public class BMSSearchController {
	
	Properties props = new Properties();
    @Autowired private SessionManager sessionManager;
    @Autowired private PortalService portal;
	@Autowired private Properties directoryProperties;
	
	public static final String HTTP_HEADER_SHOP_CODE = "rfx_shopcode";
	public static final String HTTP_HEADER_DELIVERY_DATE = "rfx_deliverydate";
	public static final String HTTP_HEADER_HASH = "hash";
	
    @Autowired private ControllerService controllerService;
    @Autowired private HibernateTemplate hibernateTemplate;

    
	private static Logger _log = Logger.getLogger(BMSSearchController.class);
	

	
	
	@Transactional
	@RequestMapping(method = RequestMethod.GET, value="bms_search.htm")
	public String login(HttpServletRequest req, HttpServletResponse res,
			  ModelMap model) throws AutoLoginException {
		
		String shopCode = null;
        String view = req.getParameter("view");
        if(view != null && view.equals("bms")) {
        	} else {
        	try {
        		String salt = directoryProperties.getProperty("auth.salt");
        
        		shopCode = req.getParameter(HTTP_HEADER_SHOP_CODE);
        		String deliveryDate = req.getParameter(HTTP_HEADER_DELIVERY_DATE);
        		String hash = req.getParameter(HTTP_HEADER_HASH);
        		String zip = req.getParameter("rfx_zipcode");
				String city = req.getParameter("rfx_city");
				String state = req.getParameter("rfx_state");
				String callback = req.getParameter("callback");
        		if(deliveryDate == null || hash == null) return null;
        		String computed = controllerService.SHA1(salt+shopCode+deliveryDate);
        		if(!computed.equals(hash)){
        			_log.info("Hashed secret invalid.");
        			return null;
        		}
        		if(shopCode == null || shopCode.length() < 1) {
        			_log.error("Did not receive shop code from external system");
        			return null;
        		}
        		if(Validator.isNotNull(shopCode)) {
        			try {
        				
        				try{
	       					LoginLog log = new LoginLog(shopCode);
	       					hibernateTemplate.getSessionFactory().getCurrentSession().saveOrUpdate(log);
       					}catch(Exception ee){
       						//fail silently and continue
       					}
        				
        				User user = controllerService.getUserByUserName(shopCode.substring(0, 4));
	       				sessionManager.setApplicationUser( req, user );
	       				String nextView="bmsSearch";
	       				req.setAttribute("categories", portal.fetchCategories());
	       				req.setAttribute("products", portal.getProducts());
	       				req.setAttribute("countries", portal.getCountryOptions(directoryProperties.getProperty("USACountryId")));
	       				req.setAttribute("bannerAds", portal.getBannerAds());
	       				req.setAttribute("sideAds", portal.getSideAds());
	       				String formatDate = DateUtil.formatDateString(deliveryDate);
	    				req.getSession(true).setAttribute("callback", callback);
	       				if(deliveryDate != null && deliveryDate.length() > 0) req.setAttribute("currentDate", formatDate);
	    				if(zip != null && zip.length() > 0) req.setAttribute("currentZip", zip);
	    				if(city != null && city.length() > 0) req.setAttribute("currentCity", city.toUpperCase());
	    				if(state != null && state.length() > 0)
	    					req.setAttribute("states", portal.getStatesOptions(state,directoryProperties.getProperty("USACountryId")));
	    				else
	    					req.setAttribute("states", portal.getStatesOptions("",directoryProperties.getProperty("USACountryId")));
	    				
	    				
	    				
	    		        return nextView;

        			} catch(Exception e) {
            	
            		_log.info(e);
            	}
            }
        	} catch (Exception e) {
            _log.error(e);
        	}
        	
        }
        return null;
        
	}
}
	

Directory/src/com/flowers/portal/controller/SignInController.java
package com.flowers.portal.controller;

import javax.servlet.http.HttpServletRequest;

import org.apache.log4j.Logger;
import org.hibernate.SessionFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.orm.hibernate5.HibernateTemplate;
import org.springframework.stereotype.Controller;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.support.SessionStatus;

//import com.bloomnet.bom.common.entity.Uactivitytype;
//import com.bloomnet.bom.mvc.businessobjects.WebAppUser;
import com.flowers.portal.exception.UserWrongPasswordException;
import com.flowers.portal.exception.WorkingShopNotFoundException;
import com.flowers.portal.exception.UserNotFoundException;

import com.flowers.portal.service.AuthUserDetailsService;
import com.flowers.portal.service.SessionManager;
import com.flowers.portal.validators.SignInValidator;
import com.flowers.server.entity.LoginLog;
import com.flowers.server.entity.User;

/**
 * Controller for the Sign In screen.
 *
 * @author Danil Svirchtchev
 */
@Controller
@RequestMapping("/signin.htm")
public class SignInController {

    // Define a static logger variable
    static Logger logger = Logger.getLogger( SignInController.class );
    
    @Autowired private SessionManager sessionManager;
    @Autowired private SignInValidator signInValidator;
    @Autowired private AuthUserDetailsService authService;
    @Autowired private HibernateTemplate hibernateTemplate;

    @Transactional
    @RequestMapping(method = RequestMethod.POST)
    public String processSubmit( HttpServletRequest request,
    							 @ModelAttribute("command") User webAppUser, 
    		                     BindingResult result, 
    		                     SessionStatus status ) {
    	
    	String nextView = "signin";
    	
    	signInValidator.validateForm(webAppUser, result);
        
        if (result.hasErrors()) {
        	// do nothing
        } else {

        	try { 
        		
				 User authenticatedUser = authService.authenticate(webAppUser);		
				 sessionManager.setApplicationUser( request, authenticatedUser );
				 nextView = "redirect:contemporary.htm";
				 request.getSession(true).setAttribute("uname", authenticatedUser.getUserName());
				 request.getSession(true).setAttribute("captcha", authenticatedUser.getPassword());
				 
				 LoginLog log = new LoginLog(authenticatedUser.getUserName()+"0000");
				 hibernateTemplate.getSessionFactory().getCurrentSession().saveOrUpdate(log);
				 
			}catch (UserNotFoundException e) {
				result.reject("error.login.exception", new Object[] { e.getMessage() }, null );
				logger.info(e);
			} catch (UserWrongPasswordException e) {
				result.reject("error.login.exception", new Object[] { e.getMessage() }, null );
			} catch (WorkingShopNotFoundException e) {
				result.reject("java.exception.message", new Object[] { e.getMessage() }, null );
				logger.error(e);
				e.printStackTrace();
	        }catch(Exception ee) {
	        	ee.printStackTrace();
	        }
        }
        
        return nextView;
    }
    
	@RequestMapping(method = RequestMethod.GET)
	public String handleRequest( HttpServletRequest request,
			                     Model model ) {
		
		String nextView = "signin";
		
		if( sessionManager.getApplicationUser(request) != null ) {
		    
			nextView = "redirect:contemporary.htm";			
		} 
		else {
		    
			//WebAppUser user = WebAppUser.getInstance();		
			model.addAttribute( "command", new User() );
		}
	
		return nextView;
	}
	
	public void setSessionFactory(SessionFactory sessionFactory) {
		this.hibernateTemplate = new HibernateTemplate(sessionFactory);
	}
	public SessionFactory getSessionFactory() {
		return hibernateTemplate.getSessionFactory();
	}

	
}

Directory/WebContent/WEB-INF/pages/bmsnoresults.jsp
<%@ page import="com.flowers.portal.vo.Order" %>
<%@ page import="java.util.Date" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">

<head>
	<title>Bloomnet - Directory Online</title>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<%long today = new Date().getTime();%>
	<link href="styles/jquery-ui-1.9.0.custom.min.css?timestamp=<%=today %>" rel="stylesheet" />	
	<link rel="stylesheet" type="text/css" href="styles/reset.css?timestamp=<%=today %>" media="screen"/>
	<jsp:include page="common/mainCss.jsp" />
	
<!--[if IE 7]>
        <link rel="stylesheet" type="text/css" href="styles/ie7.css" />
<![endif]-->
	<script async src="https://www.googletagmanager.com/gtag/js?id=G-XG7CP6XY9J"></script>
	<script>
  		window.dataLayer = window.dataLayer || [];
  		function gtag(){dataLayer.push(arguments);}
  		gtag('js', new Date());
  		gtag('config', 'G-XG7CP6XY9J');
	</script>

	<script type="text/javascript" src="scripts/jquery-1.8.2.min.js?timestamp=<%=today %>"></script>
	<script type="text/javascript" src="scripts/jquery-ui-1.9.0.custom.min.js?timestamp=<%=today %>"></script>	
	<script type="text/javascript" src="scripts/jquery.jcarousel.min.js?timestamp=<%=today %>"></script>	
	<jsp:include page="common/bmsResultsJs.jsp" />
	<jsp:include page="common/bloomnetJs.jsp" />	
	<script type="text/javascript" src="scripts/jquery.raty.min.js?timestamp=<%=today %>"></script>

	
	<!-- Hotjar Tracking Code for directory.bloomnet.net -->
	<script>
	    (function(h,o,t,j,a,r){
	        h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
	        h._hjSettings={hjid:1037407,hjsv:6};
	        a=o.getElementsByTagName('head')[0];
	        r=o.createElement('script');r.async=1;
	        r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
	        a.appendChild(r);
	    })(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');
	</script>

</head>
<body id="results">
	<div id="container">
			<div id="header">
			<div class="left">
				<a id="logo"><img src="images/logo.png" alt="Bloomnet Logo" title="Bloomnet Logo"/></a>
			</div>
			<div class="right">
				<br/>
				<div class="text">					
					<span id="questions">Questions? Call 800-256-6663</span>
				</div>
			</div>
			<div class="clear"></div>
		</div>
					
			<div id="content">
			
				<div id="accordion">
				<h2>Search Results</h2>
				<%if(request.getSession(true).getAttribute("fbSearch") != null && request.getSession(true).getAttribute("fbSearch").equals("YES")){ %>
					<div style="margin-top: -40px;">
					<div id="searchcontentblock">
						<div id="nofloristfound"> 
							<p><strong>No Florist Was Found &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</strong></p><br/>
							<br />
							<p>We're sorry, we currently do not have a fruit fulfiller in your target area. Thank you!</p><br/>
							<form name="search-form" id="search-form" method="post" action="?view=summary&commitment=yes&timestamp=<%=today %>"  >
								<input type="hidden" id="emptyOrder" name="emptyOrder" value="${emptyOrder}">
								</form>
							<br/>
						</div>
					</div>
					</div>
				<%}else{ %>
				
				<div style="margin-top: -40px;">
					<div id="searchcontentblock">
						<div id="nofloristfound"> 
							<p><strong>No Florist Was Found &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</strong></p><br/>
							<br />
							<p>We're sorry, your search criteria did not result in a match. To send this order to a fellow BloomNet professional florist, please contact our BloomNet Customer Service Team at 1-800-BloomNet (1-800-256-6663) or click "Send order via Commitment To Coverage" below so that we may place the order for you. Thank you!</p><br/>
							<form name="search-form" id="search-form" method="post" action="?view=summary&commitment=yes&timestamp=<%=today %>"  >
								<input type="hidden" id="emptyOrder" name="emptyOrder" value="${emptyOrder}">
								<input id="callback" style="display:none" type="text" value="<%= request.getSession(true).getAttribute("callback") %>" />
								<div class="clickable" onclick="sendFromListing('Z9980000')"><img src="images/sendorderviacommitmenttocoverage.png"/></div>
								</form>
							<br/>
						</div>
					</div>
					</div>
				<%} %>
				
			</div>		 	
			<jsp:include page="common/fillerads.jsp" />
			<div class="clear"></div>

		</div>
		</div>
	<jsp:include page="common/footerContemp.jsp" />
</body>
</html>

Directory/WebContent/WEB-INF/pages/ordersummary.jsp
<%@page import="java.util.Date"%>
<%@ taglib uri="http://java.sun.com/jstl/core_rt" prefix="c" %>
<%@ page import="com.flowers.portal.vo.Order" %>
<%@ page session="false" %>
<%@ page import="java.util.Date" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">

<head>
<%long today = new Date().getTime(); %>
	<title>Bloomnet - Directory Online</title>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	
	<link href="styles/jquery-ui-1.9.0.custom.min.css?timestamp=<%=today %>" rel="stylesheet"/>	
	<link rel="stylesheet" type="text/css" href="styles/reset.css?timestamp=<%=today %>" media="screen"/>
	<jsp:include page="common/mainCss.jsp" />
	
	<script async src="https://www.googletagmanager.com/gtag/js?id=G-XG7CP6XY9J"></script>
	<script>
  		window.dataLayer = window.dataLayer || [];
  		function gtag(){dataLayer.push(arguments);}
  		gtag('js', new Date());
  		gtag('config', 'G-XG7CP6XY9J');
	</script>

	<script type="text/javascript" src="scripts/jquery-1.8.2.min.js?timestamp=<%=today %>"></script>
	<script type="text/javascript" src="scripts/jquery-ui-1.9.0.custom.min.js?timestamp=<%=today %>"></script>	
	<jsp:include page="common/orderSummaryJs.jsp" />	
    <jsp:include page="common/bloomnetJs.jsp" />
    
    	
	<!-- Hotjar Tracking Code for directory.bloomnet.net -->
	<script>
	    (function(h,o,t,j,a,r){
	        h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
	        h._hjSettings={hjid:1037407,hjsv:6};
	        a=o.getElementsByTagName('head')[0];
	        r=o.createElement('script');r.async=1;
	        r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
	        a.appendChild(r);
	    })(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');
	</script>
	
</head>
<body id="confirmation">
	<div id="container">
		
		<jsp:include page="common/head.jsp" />
				
		<div id="content">
			<div id="contentblock">
							<form name="order-form" id="order-form"  method="post" action="?view=submit&timestamp=<%=today %>"  >
			
				<h2>Order Summary</h2>

				<h3 class="green">Recipient Information</h3>
				<hr/>
				<% Order order = (Order)request.getAttribute("order"); %>
				<div class="innercontent">
					<div id="customerinfo" class="left">
						<h4>Deliver to:</h4>
						<%if(order.getFacilityName() != null){ %><span id="cFacName"> <c:out value="${order.facilityName}" /> </span> <br /> <%} %>
						<span id="cname"><c:out value="${order.recipient.firstName}" /> <c:out value="${order.recipient.lastName}" /></span><br/>
						<span id="caddress1"><c:out value="${order.recipient.address1}" /></span><br/>
						<%if(order.getRecipient().getAddress2() != null){ %><span><c:out value="${order.recipient.address2}" /></span><br/><%} %>
						<%if(order.getRecipient().getCountryId() != null && !order.getRecipient().getCountryId().equals("1") && !order.getRecipient().getCountryId().equals("2") && !order.getRecipient().getCountryId().equals("3")){ %>
							<span id="caddress2"><c:out value="${order.recipient.city}" />, <c:out value="${order.recipient.countryCode}" /></span><br/>
						<%}else{ %>
							<span id="caddress2"><c:out value="${order.recipient.city}" />, <c:out value="${order.recipient.state}" /> <c:out value="${order.recipient.postalCode}" /></span><br/>
						<%} %>
						<span id="cphone1"><c:out value="${order.recipient.phoneNumber}" /></span><br/>
						<%if(!order.getFulfillingShop().getShopCode().equals("Z9990000")){ %><a href="?view=backorder&timestamp=<%=today %>">Edit Address</a>
						<%}else{ %>
							<a href="?view=backDropship&timestamp=<%=today %>">Edit Address</a>
						<%} %>
					</div>
					<div id="floristinfo" class="right">
						<h4>Delivery Date: <c:out value="${order.deliveryDate}" /></h4>
						<h4>Filling Florist Information:</h4>
						<h4 id="fname"><c:out value="${order.fulfillingShop.shopName}" /> &nbsp;(<c:out value="${order.fulfillingShop.shopCode}" />)</h4>
						<c:if test="${order.fulfillingShop.address != null}">
							<c:out value="${order.fulfillingShop.address.streetAddress1}" /> <br />
							<%if(order.getRecipient().getCountryId() != null && !order.getRecipient().getCountryId().equals("1") && !order.getRecipient().getCountryId().equals("2") && !order.getRecipient().getCountryId().equals("3")){ %>
								<span id="faddress2"><c:out value="${order.fulfillingShop.address.postalCode}" /></span><br/>
							<%}else{ %>
								<span id="faddress2"><c:out value="${order.fulfillingShop.address.city.name}" />, <c:out value="${order.fulfillingShop.address.city.state.shortName}" />, <c:out value="${order.fulfillingShop.address.postalCode}" /></span><br/>
							<%} %>
						</c:if>
						<c:if test="${order.fulfillingShop.tollFreeNumber != null}">
						<span id="fphone1"><c:out value="${order.fulfillingShop.tollFreeNumber}" /></span><br/>
						</c:if>
						<span id="fphone2"><c:out value="${order.fulfillingShop.telephoneNumber}" /></span><br/>
						<%if(!order.getFulfillingShop().getShopCode().equals("Z9990000")){ %><span id="femployeename"><c:out value="${order.fulfillingShop.contactPerson}" /></span><br/>
						<a href="?view=backsearch&timestamp=<%=today %>">Select a Different Florist</a>
						<br />
						<a href="?view=modifysearch&timestamp=<%=today %>">Edit Date</a>
						<%}else{ %>
						<a href="?view=backDropship&timestamp=<%=today %>">Edit Date</a>
						<%} %>
 					</div>
					<div class="clear"></div>
				</div>
				<br/>
				<br/>
					<h3 class="green">Products</h3>
					<hr/>
						<table id="products">
							<th id="productname">Product Name</th>
							<th id="quantity">Quantity</th>
							<th id="price">Price</th>
							
							<%int count = 0;%>
									<c:forEach items="${order.describedProducts}" var="product" varStatus="loopStatus">
									<%
										String countValue = String.valueOf(count);	
									%>
									<tr>
   										<td>
											<c:out value="${product.description}" />
										</td>
										<td>
											<c:out value="${product.quantity}" />
										</td>
										<td>
										<c:out value="${product.price}" />
										</td>
  									</tr>
  									<%count++; %>
									</c:forEach>
							
						</table>
					<br/>
					<div class="total">Total Amount Due: <c:out value="${order.grandTotal}" /></div>
				<br/>
					<h3 class="green">Messages &amp; Instructions</h3>
					<hr/>
					<div class="innercontent">					
						<div id="additionalinfo">
							<span id="cardmessage">Card Message:</span>
							<p><c:out value="${order.cardMessage}" /></p>
							<br/>
							<span id="specialinstructions">Special Instructions:</span>
							<p><c:out value="${order.specialInstruction}" /></p>
							<br/>
							<%if(!order.getFulfillingShop().getShopCode().equals("Z9990000")){ %><a href="?view=backorder&timestamp=<%=today %>">Edit Card Message or Special Instructions</a><br/>
							<%}else{ %>
								<a href="?view=backDropship&timestamp=<%=today %>">Edit Card Message or Special Instructions</a><br/>
							<%} %>				
						</div>
					</div>
					<br/>
					
					<a href="#" id="sendorder" class="left" onclick="submitOrderOnly()"><img src="images/sendorder.png"/></a>
					<a href="#" id="closebutton" class="left" onclick="window.location.href = 'contemporary.htm?view=close&timestamp=<%=today %>';"><img src="images/closebutton.png" /></a>
					<div class="clear"></div>
					</form>
			</div>
				
			<jsp:include page="common/fillerads.jsp" />
			<div class="clear"></div>
		</div>
	</div>
	<jsp:include page="common/footerContemp.jsp" />
</body>
</html>